--[[
An icon for every menu row, keyed on KOReader's own menu ids.

WHY IDS AND NOT TITLES

A title is translated and a title is edited; an id is neither. Keying on text
would give English readers icons and everybody else blanks, and would go quietly
wrong the first time upstream reworded something.

WHERE THE LIST CAME FROM

Every id in `frontend/ui/elements/filemanager_menu_order.lua` and
`reader_menu_order.lua`, which is the authoritative ordering KOReader builds its
menus from -- 198 of them, read off the device rather than collected by hand, so
nothing is missing because nobody thought of it.

WHY NO NEW FONT

`fonts/nerdfonts/symbols.ttf` already ships with the plugin and already carries
679 glyphs in the Font Awesome range. Every codepoint below was checked against
that file's cmap before being written here, so none of these render as a
missing-glyph box. Three first choices were Font Awesome 5 icons the bundled
subset does not have -- a palette, a ruler and a highlighter -- and were
replaced with contrast, arrows and a pencil rather than left to fail.

REPEATS ARE DELIBERATE

Several ids share a glyph, because several rows are the same idea seen twice:
every dictionary entry gets the book, every gesture entry the hand, every
history the clock-arrow. An icon per row that has no relation to its neighbours
is decoration; a repeated one is a category.
]]

-- Two sources, and the second is why the first was not enough.
--
-- KOReader's own ids come from its menu-order files. Everything a PLUGIN
-- registers is absent from those, because a plugin attaches its entries at run
-- time -- so the rows this fork adds itself, and xtreader's, had no icons while
-- the stock ones around them did. Ids were added to both plugins for this;
-- neither had needed one before.
return {
    about                                        = "\u{F05A}",
    advanced_settings                            = "\u{F0AD}",
    android_back_button                          = "\u{F11C}",
    android_haptic_feedback                      = "\u{F11C}",
    android_volume_keys                          = "\u{F11C}",
    auto_frontlight                              = "\u{F185}",
    autodim                                      = "\u{F185}",
    autoshutdown                                 = "\u{F011}",
    autostandby                                  = "\u{F236}",
    autosuspend                                  = "\u{F236}",
    autoturn                                     = "\u{F021}",
    autowarmth                                   = "\u{F185}",
    back_in_filemanager                          = "\u{F060}",
    back_in_reader                               = "\u{F060}",
    back_to_exit                                 = "\u{F08B}",
    backspace_as_back                            = "\u{F11C}",
    battery_statistics                           = "\u{F240}",
    book_info                                    = "\u{F05A}",
    book_map                                     = "\u{F279}",
    book_shortcuts                               = "\u{F0C1}",
    book_status                                  = "\u{F05A}",
    bookmark_browser                             = "\u{F02E}",
    bookmark_browsing_mode                       = "\u{F02E}",
    bookmark_search                              = "\u{F002}",
    bookmarks                                    = "\u{F02E}",
    bookmarks_settings                           = "\u{F02E}",
    calibre                                      = "\u{F02D}",
    change_font                                  = "\u{F031}",
    charging_led                                 = "\u{F0EB}",
    cloud_storage                                = "\u{F0C2}",
    cloudstorage                                 = "\u{F0C2}",
    collections                                  = "\u{F07C}",
    color_rendering                              = "\u{F042}",
    cover_events                                 = "\u{F03E}",
    coverimage                                   = "\u{F03E}",
    developer_options                            = "\u{F121}",
    device                                       = "\u{F10B}",
    device_status_alarm                          = "\u{F0F3}",
    dictionary_lookup                            = "\u{F02D}",
    dictionary_lookup_history                    = "\u{F1DA}",
    dictionary_settings                          = "\u{F013}",
    djvu_render_mode                             = "\u{F03E}",
    doc_setting_tweak                            = "\u{F013}",
    document                                     = "\u{F15C}",
    document_auto_save                           = "\u{F0C7}",
    document_end_action                          = "\u{F11E}",
    document_metadata_arc                        = "\u{F187}",
    document_metadata_location                   = "\u{F07C}",
    document_metadata_location_move              = "\u{F07C}",
    document_settings                            = "\u{F15C}",
    exit                                         = "\u{F08B}",
    exit_menu                                    = "\u{F08B}",
    exporter                                     = "\u{F093}",
    external_keyboard                            = "\u{F11C}",
    favorites                                    = "\u{F004}",
    file_ext_assoc                               = "\u{F15B}",
    file_search                                  = "\u{F002}",
    file_search_results                          = "\u{F002}",
    filebrowser_settings                         = "\u{F07C}",
    filemanager                                  = "\u{F07C}",
    filemanager_display_mode                     = "\u{F00A}",
    filemanager_settings                         = "\u{F013}",
    find_book_in_calibre_catalog                 = "\u{F02D}",
    follow_links                                 = "\u{F0C1}",
    font_ui_fallbacks                            = "\u{F031}",
    frontlight                                   = "\u{F185}",
    fullscreen                                   = "\u{F065}",
    fulltext_search                              = "\u{F002}",
    fulltext_search_findall_results              = "\u{F002}",
    fulltext_search_settings                     = "\u{F013}",
    gesture_intervals                            = "\u{F25A}",
    gesture_manager                              = "\u{F25A}",
    gesture_overview                             = "\u{F25A}",
    go_to                                        = "\u{F124}",
    go_to_next_location                          = "\u{F061}",
    go_to_previous_location                      = "\u{F060}",
    handmade_hidden_flows                        = "\u{F070}",
    handmade_settings                            = "\u{F03A}",
    handmade_toc                                 = "\u{F03A}",
    help                                         = "\u{F059}",
    hide_nonlinear_flows                         = "\u{F070}",
    highlight_options                            = "\u{F040}",
    history                                      = "\u{F1DA}",
    ignore_battery_optimizations                 = "\u{F240}",
    ignore_hold_corners                          = "\u{F25A}",
    ignore_open_sleepcover                       = "\u{F02D}",
    ignore_sleepcover                            = "\u{F02D}",
    keep_alive                                   = "\u{F06E}",
    keyboard_layout                              = "\u{F11C}",
    language                                     = "\u{F0AC}",
    language_support                             = "\u{F0AC}",
    long_press                                   = "\u{F25A}",
    main                                         = "\u{F0C9}",
    mass_storage_actions                         = "\u{F0A0}",
    mass_storage_settings                        = "\u{F0A0}",
    menu_activate                                = "\u{F0C9}",
    more_tools                                   = "\u{F0AD}",
    move_to_archive                              = "\u{F187}",
    navi                                         = "\u{F14E}",
    navi_settings                                = "\u{F14E}",
    navigation                                   = "\u{F14E}",
    network                                      = "\u{F1EB}",
    network_after_wifi_action                    = "\u{F1EB}",
    network_before_wifi_action                   = "\u{F1EB}",
    network_dismiss_scan                         = "\u{F00D}",
    network_info                                 = "\u{F05A}",
    network_powersave                            = "\u{F0E7}",
    network_proxy                                = "\u{F0AC}",
    network_restore                              = "\u{F021}",
    network_wifi                                 = "\u{F1EB}",
    news_downloader                              = "\u{F09E}",
    night_mode                                   = "\u{F186}",
    opds                                         = "\u{F19C}",
    open_last_document                           = "\u{F07C}",
    open_previous_document                       = "\u{F07C}",
    opening_page_location_stack                  = "\u{F1DA}",
    ota_update                                   = "\u{F019}",
    page_browser                                 = "\u{F00A}",
    page_map                                     = "\u{F279}",
    page_overlap                                 = "\u{F24D}",
    page_turns                                   = "\u{F064}",
    pageturn_power                               = "\u{F11C}",
    panel_zoom_options                           = "\u{F00E}",
    partial_rerendering                          = "\u{F021}",
    patch_management                             = "\u{F0AD}",
    physical_buttons_setup                       = "\u{F11C}",
    plugin_management                            = "\u{F12E}",
    plugins_disable_external                     = "\u{F12E}",
    plus_menu                                    = "\u{F067}",
    poweroff                                     = "\u{F011}",
    press                                        = "\u{F25A}",
    profiles                                     = "\u{F007}",
    progress_sync                                = "\u{F021}",
    qrclipboard                                  = "\u{F029}",
    quickstart_guide                             = "\u{F02D}",
    read_timer                                   = "\u{F017}",
    reboot                                       = "\u{F021}",
    report_bug                                   = "\u{F188}",
    restart_koreader                             = "\u{F021}",
    reverse_sorting                              = "\u{F0DC}",
    screen                                       = "\u{F108}",
    screen_disable_double_tap                    = "\u{F25A}",
    screen_dpi                                   = "\u{F108}",
    screen_eink_opt                              = "\u{F108}",
    screen_notification                          = "\u{F0F3}",
    screen_rotation                              = "\u{F021}",
    screen_timeout                               = "\u{F017}",
    screensaver                                  = "\u{F186}",
    screenshot                                   = "\u{F030}",
    scrolling                                    = "\u{F07D}",
    search                                       = "\u{F002}",
    search_menu                                  = "\u{F002}",
    search_settings                              = "\u{F013}",
    selection_text                               = "\u{F040}",
    set_render_style                             = "\u{F1FC}",
    setting                                      = "\u{F013}",
    show_filter                                  = "\u{F0B0}",
    skim_dialog_position                         = "\u{F124}",
    skim_to                                      = "\u{F124}",
    sleep                                        = "\u{F236}",
    sort_by                                      = "\u{F0DC}",
    sort_mixed                                   = "\u{F0DC}",
    speed_reading_module_perception_expander     = "\u{F04B}",
    ssh                                          = "\u{F120}",
    start_bq                                     = "\u{F04B}",
    start_content_selection                      = "\u{F040}",
    start_with                                   = "\u{F015}",
    statistics                                   = "\u{F080}",
    status_bar                                   = "\u{F0CA}",
    style_tweaks                                 = "\u{F1FC}",
    switch_zoom_mode                             = "\u{F00E}",
    synchronize_time                             = "\u{F017}",
    system_statistics                            = "\u{F080}",
    table_of_contents                            = "\u{F03A}",
    taps_and_gestures                            = "\u{F25A}",
    terminal                                     = "\u{F120}",
    text_editor                                  = "\u{F044}",
    time                                         = "\u{F017}",
    toc_alt_toc                                  = "\u{F03A}",
    toc_items_font_size                          = "\u{F031}",
    toc_items_per_page                           = "\u{F03A}",
    toc_items_show_chapter_length                = "\u{F03A}",
    toc_items_with_dots                          = "\u{F03A}",
    toc_ticks_level_ignore                       = "\u{F03A}",
    toggle_bookmark                              = "\u{F02E}",
    tools                                        = "\u{F0AD}",
    translate_current_page                       = "\u{F0AC}",
    translation_settings                         = "\u{F0AC}",
    typeset                                      = "\u{F031}",
    typography                                   = "\u{F031}",
    units                                        = "\u{F0B2}",
    up                                           = "\u{F062}",
    version                                      = "\u{F05A}",
    vocabbuilder                                 = "\u{F02D}",
    wallabag                                     = "\u{F0C1}",
    wikipedia_history                            = "\u{F1DA}",
    wikipedia_lookup                             = "\u{F266}",
    wikipedia_settings                           = "\u{F013}",
    bookshelf_about                              = "\u{F05A}",
    bookshelf_hardcover                          = "\u{F02D}",
    bookshelf_settings                           = "\u{F013}",
    bookshelf_shelf_size                         = "\u{F00A}",
    bookshelf_shelf_tabs                         = "\u{F02C}",
    bookshelf_toggle                             = "\u{F00D}",
    bookshelf_updates                            = "\u{F019}",
    kindleui                                     = "\u{F108}",
    kindleui_lock_screen                         = "\u{F023}",
    kindleui_restart                             = "\u{F021}",
    kindleui_show_cc                             = "\u{F0CA}",
    kindleui_suppress_menu                       = "\u{F070}",
    kindleui_swipe_down                          = "\u{F063}",
    kindleui_swipe_up                            = "\u{F062}",
    kindleui_tap_top                             = "\u{F25A}",
    reading_insights_popup                       = "\u{F080}",
    xtreader                                     = "\u{F0C2}",
    xtreader_auto_dl                             = "\u{F019}",
    xtreader_background                          = "\u{F017}",
    xtreader_books_dir                           = "\u{F07C}",
    xtreader_formats                             = "\u{F15B}",
    xtreader_kosync                              = "\u{F021}",
    xtreader_pair                                = "\u{F029}",
    xtreader_server                              = "\u{F233}",
    xtreader_skip                                = "\u{F07C}",
    xtreader_stats                               = "\u{F080}",
    xtreader_status                              = "\u{F05A}",
    xtreader_sync_books                          = "\u{F02D}",
    xtreader_sync_now                            = "\u{F021}",
    xtreader_unpair                              = "\u{F127}",
    xtreader_upload                              = "\u{F093}",
    xtreader_upload_check                        = "\u{F002}",
    xtreader_wall_dir                            = "\u{F07C}",
    xtreader_wallpapers                          = "\u{F03E}",
}
